# Swag Docker Compose File
# Adapted from https://docs.linuxserver.io/general/swag
---
version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - URL=notifiarr.com
      - SUBDOMAINS=wildcard
      - EXTRA_DOMAINS=mybakerspro.com,*.mybakerspro.com,customsweetsntreats.com,*.customsweetsntreats.com,notifiarr.wiki,*.notifiarr.wiki,discordnotifier.com,*.discordnotifier.com,*.notifiarr.app
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - /home/swag/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  auth-proxy:
    image: docker.io/golift/mysql-auth-proxy
    container_name: auth
    environment:
      - MYSQL_HOST=notifiarr:3306
      - MYSQL_NAME=notifiarr
      - MYSQL_USER=proxy
      - MYSQL_PASS_FILE=/mysqlsecret
      - SECRET_FILE=/password
      - LOG_FILE=/logs/access.log
      - ERROR_FILE=/logs/error.log
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - /home/swag/.mysqlsecret:/mysqlsecret:ro
      - /home/swag/.password:/password:ro
      - /home/swag/config/log/authproxy:/logs

  cloudflare-ddns:
    image: oznu/cloudflare-ddns
    container_name: ddns
    env_file:
      - /home/swag/.env-cloudflare-ddns
    restart: unless-stopped
  golift:
    image: golift/turbovanityurls:unstable
    container_name: golift
    environment:
      - PORT=8081
    ports: 
      - 8081:8081
    volumes:
      - /usr/local/etc/turbovanityurls/config.yaml:/home/swag/golift/config.yaml
