# Swag Docker Compose File
# Adapted from https://docs.linuxserver.io/general/swag
---
version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - URL=notifiarr.com
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - /home/swag/config:/config
    ports:
      - 443:443
    restart: unless-stopped
